In [1]:
import igl
import meshplot as mp
import numpy as np
import numpy.linalg as LA
from meshplot import plot

In [2]:
# loading and plotting mesh
vert, tri = igl.read_triangle_mesh("./igea.ply")
print(vert)                                               #nx3 array containing the 3D vertex coordinates
print(vert.shape)
#print(type(vert))
print(tri)                                                # mx3 containing the triangles
print(tri.shape)
#print(type(tri))
plot_mesh = mp.plot(vert, tri)


[[ 0.1522277  -1.10341821  0.21488196]
 [ 0.1576865  -1.10406037  0.2063322 ]
 [ 0.16346392 -1.10369255  0.20969022]
 ...
 [-0.03452438  0.99575616  0.29919739]
 [-0.04053583  0.99748553  0.29668082]
 [ 0.0097354   0.98900244  0.29643626]]
(134345, 3)
[[     0      1      2]
 [     2      1      3]
 [     2      3      4]
 ...
 [134327 134331 134325]
 [ 10780 134335  10781]
 [133838 134344 133836]]
(268686, 3)


Renderer(camera=PerspectiveCamera(children=(DirectionalLight(color='white', intensity=0.6, position=(-0.021590…

In [ ]:
# implement away
# do not use other functions than provided by basic python or numpy 
# (especially not the gaussian curvature function provided by igl)

def gaussian (ver, triagl):
    for i in ver:
        print(i)
    return i

g = gaussian(vert, tri)

In [3]:
k = igl.gaussian_curvature(vert, tri)
#print(vert, tri, k)
print(k)
print()
print(k.shape)
#plot(vert, tri, k)




[ 0.00947098  0.01169402  0.00610402 ...  0.01208209  0.01030115
 -0.00684498]

(134345,)


NameError: name 'gaussian' is not defined

In [5]:
# plot curvature function on the surface (cutting off extreme values)
#colors = mp.utils.get_colors(g, colormap='viridis', normalize=False, vmin=-200, vmax=200)
colors = mp.utils.get_colors(k, colormap='viridis', normalize=False, vmin=-200, vmax=200)
mp.plot(vert, tri, c=colors)


Renderer(camera=PerspectiveCamera(children=(DirectionalLight(color='white', intensity=0.6, position=(-0.021590…

In [ ]:
G= []
for i in range(50):
    theta =0
    area = 0
    for k in range(len(tri)):
        if (i in tri[k]):
            V_1 = vert[tri[k][0]] - vert[i]
            V_2 = vert[tri[k][1]] - vert[i]
            V_3 = vert[tri[k][2]] - vert[i]
            
            if np.array_equal(V_1, np.zeros(3)):
                inner = np.inner(V_2, V_3)
                norms = LA.norm(V_2)* LA.norm(V_3)
                cos = inner/norms
                rad = np.arccos(np.clip(cos, -1.0, 1.0))
                area = 0.5*LA.norm(np.cross(V_2,V_3))

            elif np.array_equal(V_2, np.zeros(3)):
                inner = np.inner(V_1, V_3)
                norms = LA.norm(V_1)* LA.norm(V_3)
                cos = inner/norms
                rad = np.arccos(np.clip(cos, -1.0, 1.0))
                area = 0.5*LA.norm(np.cross(V_1,V_3))
            else:
                inner = np.inner(V_1, V_2)
                norms = LA.norm(V_1)* LA.norm(V_2)
                cos = inner/norms
                rad = np.arccos(np.clip(cos, -1.0, 1.0))
                area = 0.5*LA.norm(np.cross(V_1,V_2))

            theta += rad
            area  += area 
            total_area = (1/3)*area
        else:
            pass
    K= ((2*(np.pi)) - theta)/ total_area
    G.append(K)
G = np.asarray(G)
print(G)
print(G.shape)

In [ ]:
import numpy as np
import numpy.linalg as LA

a = np.array([-0.01123621, 0.00027435,  0.00519174])
b = np.array([-0.00577741, -0.00036782, -0.00335802])

inner = np.inner(a, b)
norms = LA.norm(a) * LA.norm(b)

cos = inner / norms
rad = np.arccos(np.clip(cos, -1.0, 1.0))
deg = np.rad2deg(rad)
area = 0.5*LA.norm(np.cross(a,b))
print(rad)
print(deg)
G= ((2*(np.pi)) - rad)/(area)
print(G)